---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/bosh-lite-ci

inputs:
- name: bosh-src
- name: stemcell-version
outputs:
- name: out
run:
  path: bosh-src/ci/pipelines/stemcells/tasks/build-stemcell.sh
